from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1462, 890)
        MainWindow.setMinimumSize(QtCore.QSize(1462, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(1000, 826))
        self.graphicsView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.graphicsView.setMouseTracking(False)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.gridLayout_6.addLayout(self.horizontalLayout, 0, 0, 2, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 35))
        self.label_4.setStyleSheet("font-size: 10pt;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.disjoint_paths_field = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disjoint_paths_field.sizePolicy().hasHeightForWidth())
        self.disjoint_paths_field.setSizePolicy(sizePolicy)
        self.disjoint_paths_field.setMinimumSize(QtCore.QSize(430, 580))
        self.disjoint_paths_field.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.disjoint_paths_field.setStyleSheet("font-size: 12pt;")
        self.disjoint_paths_field.setObjectName("disjoint_paths_field")
        self.verticalLayout_4.addWidget(self.disjoint_paths_field)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1462, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuGraph = QtWidgets.QMenu(self.menubar)
        self.menuGraph.setObjectName("menuGraph")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        self.menuGraph.setFont(font)
        self.menuModel.setFont(font)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_Node = QtWidgets.QAction(MainWindow)
        self.actionAdd_Node.setObjectName("actionAdd_Node")
        self.actionDelete_Node = QtWidgets.QAction(MainWindow)
        self.actionDelete_Node.setObjectName("actionDelete_Node")
        self.actionAdd_Edge = QtWidgets.QAction(MainWindow)
        self.actionAdd_Edge.setObjectName("actionAdd_Edge")
        self.actionDelete_Edge = QtWidgets.QAction(MainWindow)
        self.actionDelete_Edge.setObjectName("actionDelete_Edge")
        self.actionAdd_Weight = QtWidgets.QAction(MainWindow)
        self.actionAdd_Weight.setObjectName("actionAdd_Weight")
        self.actionCheck_Graph = QtWidgets.QAction(MainWindow)
        self.actionCheck_Graph.setObjectName("actionCheck_Graph")
        self.actionInput_source_and_end = QtWidgets.QAction(MainWindow)
        self.actionInput_source_and_end.setObjectName("actionInput_source_and_end")
        self.actionMake_Full_Modeling = QtWidgets.QAction(MainWindow)
        self.actionMake_Full_Modeling.setObjectName("actionMake_Full_Modeling")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuGraph.addAction(self.actionAdd_Node)
        self.menuGraph.addAction(self.actionDelete_Node)
        self.menuGraph.addAction(self.actionAdd_Edge)
        self.menuGraph.addAction(self.actionDelete_Edge)
        self.menuGraph.addAction(self.actionAdd_Weight)  # new
        self.menuGraph.addAction(self.actionClear_All)
        self.menuModel.addAction(self.actionInput_source_and_end)
        self.menuModel.addAction(self.actionMake_Full_Modeling)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuGraph.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", " Result panel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuGraph.setTitle(_translate("MainWindow", "Graph"))
        self.menuModel.setTitle(_translate("MainWindow", "Model"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_Node.setText(_translate("MainWindow", "Add Node"))
        self.actionDelete_Node.setText(_translate("MainWindow", "Delete Node"))
        self.actionAdd_Edge.setText(_translate("MainWindow", "Add Edge"))
        self.actionDelete_Edge.setText(_translate("MainWindow", "Delete Edge"))
        self.actionAdd_Weight.setText(_translate("MainWindow", "Add Weight"))
        self.actionCheck_Graph.setText(_translate("MainWindow", "Check Graph"))
        self.actionInput_source_and_end.setText(_translate("MainWindow", "Input Start and End"))
        self.actionMake_Full_Modeling.setText(_translate("MainWindow", "Make Modeling"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))